### ISSUE TITLE
A little mistake

### ISSUE THREAD

**Issue by Youngv** [billie66/TLCL#5]
[![:digit:]]\*   Any file not beginning with a numeral
[![:digit:]]\*   以数字开头的文件 应该是“不以数字开头的文件”

http://billie66.github.com/TLCL/book/chap05.html 表5-3

**Comment by billie66** [comment]
You are right. Thanks!

**Comment by Youngv** [comment]
bash has a built-in help facility available for each of the shell builtins. To use it, type “help” followed by the name of the shell builtin. For example:
bash 有一个内建的帮助工具，可供每一个 shell 内部命令使用。输入”type”，接着是 shell 内部命令名。

应该是输入“help"
http://billie66.github.com/TLCL/book/chap06.html

**Comment by Youngv** [comment]
Now for our very first experience with programming! We will create a command of our own using the alias command. But before we start, we need to reveal a small command line trick. It’s possible to put more than one command on a line by separating each command with a semicolon character. It works like this:

现在是时候，感受第一次编程经历了！我们将用 alias 命令创建我们自己的命令。但在 开始之前，我们需要展示一个命令行小技巧。可以把多个命令放在同一行上，命令之间 用”:”分开。它像这样工作：

应该是命令之间用”；”分开
http://billie66.github.com/TLCL/book/chap06.html

**Comment by billie66** [comment]
Thanks for your kindness. I know there are many errors in this translation because of my carelessness and poor ability. So I am very happy that you can join and contribute to this work.  

BTW, I should apologize to you, since I didn't see your pull request before I corrected the mistake that you found.  This time you may sent pull request, then I can get your change.
